internalName: ine

locales:
  en:
    name: &bundleName "Indoeuropean Keyboards"
    description: "Mobile OS keyboards for the Indoeuropean languages from the Divvun group at UiT."
  nb:
    name: "Indoeuropeisk tastatur"
    description: "Mobiltastatur for indoeuropeiske språk fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [ine]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.ine
    icon: images/ine-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.ine
    bundleName: *bundleName
    icon: images/ine-icon.png

  osx:
    <<: *AppleID
    icon: images/ine-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "replace-with-real-uuid-one-for-each-language"
