template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 26
template_sha = "43631dc24c0223786be78636665a5316e338004b"

[replacements]
__UND2C__ = "ine"
__UNDEFINED__ = "Indo-European languages"
__UND__ = "ine"
